### ISSUE TITLE
Some colors are darker & unreadable

### ISSUE THREAD

**Issue by ahmedelgabri** [tomasiser/vim-code-dark#11]
After the changes done in https://github.com/tomasiser/vim-code-dark/pull/9 some colors are darker now & can be barley readable.

React component `.js` file
<img width="491" alt="screen shot 2017-09-28 at 17 40 35" src="https://user-images.githubusercontent.com/63876/30976145-591414a4-a474-11e7-9530-a499e7236d5a.png">

`.muttrc` file
<img width="274" alt="screen shot 2017-09-28 at 17 40 53" src="https://user-images.githubusercontent.com/63876/30976146-59148bfa-a474-11e7-8c2c-4717ba49954c.png">

`.vimrc` file
<img width="434" alt="screen shot 2017-09-28 at 17 46 59" src="https://user-images.githubusercontent.com/63876/30976438-16f74e1e-a475-11e7-93b2-35f3a4f7b38d.png">

**Comment by tomasiser** [comment]
It was most likely because #9 changed `Type`, which is used globally by other languages as well. I have removed the new color definition. Could you verify the issue is now ok?

**Comment by ahmedelgabri** [comment]
Yes, now it's working fine. Thanks! 👍
