### ISSUE TITLE
Any chance to support VSCode Dark+ V2?

### ISSUE THREAD

**Issue by sairajchouhan** [tomasiser/vim-code-dark#113]
VSCode got a new Dark+ v2, any change to add it?

<img width="1512" alt="Screenshot 2023-02-27 at 6 52 38 PM" src="https://user-images.githubusercontent.com/57995897/221574747-3fa28f97-faf5-4941-ad82-ea79fdb78024.png">

**Comment by tomasiser** [comment]
Hi, I have just noticed a week ago that Visual Studio Code is adopting new colors. I think it'd be great to eventually adopt them and offer a switch for users to choose between the old and new colors. It would be best if we could just get a diff of the old vs. new colors somewhere from within VS Code's source codes.

**Comment by saccarosium** [comment]
I've confronted the two theme and the only thing that seems to change is the background and the UI contrast. This would be extremely easy to implement if it stays this way; but since is marked _experimental_, I think is safer to wait until it is official.

**Comment by fingolfin19** [comment]
Just happened to notice that the new themes have dropped the "V2(experimental)" and are now called Dark Modern and Light Modern.

**Comment by saccarosium** [comment]
@fingolfin19 where are you seeing this change to Dark Modern? Looking at the [source code](https://github.com/microsoft/vscode/tree/main/extensions/theme-defaults/themes) doesn't seem true. Also on VSCode is still darkV2 experimental.

<img width="602" alt="Screenshot 2023-04-28 at 21 41 55" src="https://user-images.githubusercontent.com/96259932/235238543-e84bc592-c429-4a62-a91a-b369742a2dfd.png">

**Comment by fingolfin19** [comment]
> @fingolfin19 where are you seeing this change to Dark Modern? Looking at the [source code](https://github.com/microsoft/vscode/tree/main/extensions/theme-defaults/themes) doesn't seem true. Also on VSCode is still darkV2 experimental.
> 
> <img alt="Screenshot 2023-04-28 at 21 41 55" width="602" src="https://user-images.githubusercontent.com/96259932/235238543-e84bc592-c429-4a62-a91a-b369742a2dfd.png">

Hmmm, it looks like the name of the themes have changed inside the files, but not the names of the files themselves. 

The [latest commit](https://github.com/microsoft/vscode/commit/e04309e92ac20860cd575dfdc599f1c0f36359b5) has the name changes. 

This is what I see on insiders build:
![image](https://user-images.githubusercontent.com/113927777/235243219-ca5e9da3-825d-4e6a-8835-ad6eff6f9f6a.png)

**Comment by saccarosium** [comment]
I see! When it will packaged on the regular release I will try to integrated myself.

**Comment by tubzby** [comment]
FYI, VSC switching to "dark modern" by default in latest release.

**Comment by tomasiser** [comment]
Thanks to @saccarosium, you can now try the new theme by setting `let g:codedark_modern=1` 😉

**Comment by tubzby** [comment]
Am I missing something? With or without *let g:codedark_modern=1*, it all looks the same.

I checked the RGB value of the background, it's (31, 31, 31), for VS code, it's (24, 24, 24).

**Comment by tomasiser** [comment]
Are you sure you did `let g:codedark_modern=1` before initializing the color scheme? Because the variable is checked the moment the color scheme is loaded and the default value is 0 (disabled), so changing it later has no effect.

**Comment by tubzby** [comment]
I'm using `lazy`, is this right?
<img width="738" alt="image" src="https://github.com/tomasiser/vim-code-dark/assets/16208625/81cf5d5c-d070-4eab-b148-bd5b643f72d3">

**Comment by tomasiser** [comment]
You're right that almost nothing changes and that was, I guess, intended in #117. I checked my VS Code and changing between the dark modern and dark+ themes does not really change the code area, even the background only changes between 30,30,30 and 31,31,31 RGB. I am not sure why your VS Code background is 24,24,24 RGB. 🤔

**Comment by saccarosium** [comment]
That's right the most changes are mainly in the outer UI. Since (N)vim UIs are much more bare bones I couldn't do a lot with the new changes. The most notable changes are the status line and tabbar.
