### ISSUE TITLE
Help wanted: How to tweak colours in the palette?

### ISSUE THREAD

**Issue by CharlieDerby** [tomasiser/vim-code-dark#120]
Hi, I'm happy with the colour palette mostly but I would prefer some colours, e.g. the orange for strings, to be slightly brighter. What's the best way to go about this?

Thanks.

**Comment by tomasiser** [comment]
Hello!

If you know how to use git, then the simplest solution that many people do is to simply fork (clone) this repository and then change the [`colors/codedark.vim` file](https://github.com/tomasiser/vim-code-dark/blob/master/colors/codedark.vim). For example, by examining the file, you can see on line 217 that `String` uses the `cdOrange` color, and on line 154, you can see that `cdOrange` is defined to be `#CE9178`.

If you don't know how to use git and don't want to learn, then you could also just download this plugin directly and modify the `codedark.vim` file locally on your computer and then point your Vim installation to that file manually.

**Comment by wrecklass** [comment]
A simpler work around would be to add something like the following to your own .vimrc file after the 'colorscheme codedark' line:

```vim-script
   hi String guifg='#FED198' ctermfg: 17
```
Or choose your own color, #FED198 was my own attempt at a bright orange for example.

**Comment by tomasiser** [comment]
Hi there, I am closing the issue as there was no reply, so I am considering it solved.
