### ISSUE TITLE
Search result colours

### ISSUE THREAD

**Issue by delreluca** [tomasiser/vim-code-dark#127]
When using `hlsearch` the colour of the currently selected search result is very similar to the colour of the other search results:

![image](https://github.com/user-attachments/assets/bf00ab5f-e613-47f0-adf5-a45f073c4e9c)

Is it possible to make the selected result stand out a bit more?

**Comment by delreluca** [comment]
Changing from `94` to `130` here seems to increase the contrast enough for my taste. However both the old and new version differ a bit from VSCode

https://github.com/tomasiser/vim-code-dark/blob/4624dc223bf574aa9a731c2383c579847303c380/colors/codedark.vim#L130

![image](https://github.com/user-attachments/assets/68bd1cea-596e-424f-83f5-419df4a88ced)
![image](https://github.com/user-attachments/assets/29a34f1d-e68b-4636-a4b7-6d454aa86b3e)

I’m also not sure if the change has any unintended consequences

**Comment by tomasiser** [comment]
Hello, thank you for the comment! The colors in vim are unfortunately not exactly the same as in VS Code. This color scheme is somewhat old and it's even possible that Microsoft changed a few colors meanwhile. Also, the rendering in the terminal is not identical to the Electron backend of VS Code, so at some point I noticed that even though I put the same RGB color in the color scheme, they actually look somewhat different when rendered. Also, VS Code differentiates more situations than vim, so some features are either completely ignored or changed to make sense in vim.

I am happy you found colors that work for you. At this point I guess I wouldn't introduce the change for everyone, but they can always search for your comment and adjust it for themselves if they want to!
