### ISSUE TITLE
Why not working on Microsoft's "Windows Terminal" when diffing? Or is Windows's Vim supported?

### ISSUE THREAD

**Issue by flyingosprey** [tomasiser/vim-code-dark#128]
"Windows Terminal" uses a default config json. And the .vimrc is

```
syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'tomasiser/vim-code-dark'

call vundle#end()
filetype plugin indent on

colorscheme codedark
```

This is the observation, when diffing 2 files, ""C:/Program Files/Vim/vim90/vim.exe" -d 1.c 2.c"

![image](https://github.com/user-attachments/assets/2b82cd24-cfab-423d-949d-02bbfd2228cd)

This is the observation from Linux Terminator for same .vimrc and diff files

![image](https://github.com/user-attachments/assets/9a1bd26b-d463-49b3-b9e7-33acd5399b34)

You can see that Windows' behavior is very different from Linux's, which seems wrong.

I also verify that 
1) Windows class "Command Prompt" does not work either
2) Gvim on Windows works fine.

Thanks for your suggestion.

**Comment by tomasiser** [comment]
Thank you for the report! To be honest, I never tried running it like that on Windows.

I would suggest two things:
- Could you try `:hi` to see what colors vim sees?
- Could you try `set t_Co=256` and/or `set termguicolors` separately and together?

**Comment by flyingosprey** [comment]
![image](https://github.com/user-attachments/assets/4c4e6f1e-da21-4719-baf4-f1a09177652c)
![image](https://github.com/user-attachments/assets/6f17d5a2-32d1-413c-874d-9f16ee9c72ea)
![image](https://github.com/user-attachments/assets/579b7953-393c-40c8-a5c8-75bee2a92f02)
![image](https://github.com/user-attachments/assets/df5d6c83-080d-476c-9900-b58fa912b99c)
![image](https://github.com/user-attachments/assets/30b08d86-1524-49cc-9397-fd82e16c71ed)
![image](https://github.com/user-attachments/assets/a0fa7d2a-6c1e-4a6d-a6f5-9f8c11560c38)
![image](https://github.com/user-attachments/assets/8ca34d7c-f9a8-4ce2-85c2-f669a37990c5)

I tried set t_Co=256 and set termguicolors. Either of them works

Thank you.
