### ISSUE TITLE
Markdown headings same color as plaintext

### ISSUE THREAD

**Issue by Mikkolehtimaki** [tomasiser/vim-code-dark#16]
I really like this theme, but there does not seem to be much support for markdown files. Any way to extend this scheme?

**Comment by smgallo** [comment]
I'll second this. I love the this color scheme for code development, but find the white on black in markdown mode harsh on the eyes and switch to solarized dark for markdown. I think that simply adjusting the contrast a bit would help quite a bit.

**Comment by tomasiser** [comment]
Thanks, some issues were fixed by #30. If you feel like something else should be improved, feel free to open a new issue / PR.
