### ISSUE TITLE
Everything is black with codedark in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by BerndErnst** [tomasiser/vim-code-dark#3]
I'm using Bash for Windows 10 and using codedark theme everything went black in vim.
Other themes like "more" are working without problems.
Are there any dependencies of your theme?
I did a manual wget into ~/.vim/colors

With more:
![1](https://cloud.githubusercontent.com/assets/9050259/23337313/91afb978-fbe9-11e6-9e3a-5ec454a624fe.JPG)

with codedark:
![2](https://cloud.githubusercontent.com/assets/9050259/23337314/96a687d6-fbe9-11e6-89a8-292ce8955c3e.JPG)

**Comment by tomasiser** [comment]
Hi, the problem is that vim on Bash for Windows does not support full GUI colors, but only a limited color palette. I am already working on a fix, hold on!

**Comment by BerndErnst** [comment]
Here is the output of some script I found from
Author: Todd Larason <jtl@molehill.org>
So my color palette doesn't seem to be too screwed up. And AFAIK it will try to use the next matching color, if not available. But I'm no expert in terminal color schemes

![3](https://cloud.githubusercontent.com/assets/9050259/23341736/aac0cb28-fc4d-11e6-8880-4bc7053b2f07.JPG)

**Comment by tomasiser** [comment]
I have updated the colorscheme. Try to download the newest version and put this in your `.vimrc`:

```
set t_Co=256
colorscheme codedark
```

It will try to use the closest 256 colors available. It seems to me that the newest Bash for Windows should also support even more than 256 colors, but I cannot test that right now.

Let me know if it works!

**Comment by BerndErnst** [comment]
Current status:

![4](https://cloud.githubusercontent.com/assets/9050259/23366441/fb709116-fd06-11e6-9738-cf1ff8d1003d.JPG)

**Comment by tomasiser** [comment]
Try the following commands and try to place them in your `.vimrc`:
```
set t_Co=256
set t_ut=
colorscheme codedark
```
This looks like a problem in the terminal, not in the colorscheme. See http://vi.stackexchange.com/questions/238/tmux-is-changing-part-of-the-background-in-vim.

**Comment by BerndErnst** [comment]
Thank you. And yes, the Bash Terminal on Windows is not the best one 🙄

![5](https://cloud.githubusercontent.com/assets/9050259/23393441/2309ea5c-fd83-11e6-9ae5-5eaac5a3d9cd.JPG)

**Comment by tomasiser** [comment]
Good! Glad it worked!
