### ISSUE TITLE
Conservative mode is always on.

### ISSUE THREAD

**Issue by 9527KGG** [tomasiser/vim-code-dark#34]
Observed:

In my givm, conservative mode is always on. 

![image](https://user-images.githubusercontent.com/12282281/55692380-3dc9a800-595c-11e9-9a2d-80fdc69ab9e0.png)

echo g:codedark_conservative shows 0

Expected:
The color of the function should not be white.

Any suggestion?

Ubuntu 18LTS + Xfc4. Gvim is the default one.

**Comment by 9527KGG** [comment]
This is what VS code shows:
![image](https://user-images.githubusercontent.com/12282281/55692486-70c06b80-595d-11e9-9449-5e1bb8855b06.png)

The color of the function is not white.

**Comment by 9527KGG** [comment]
"let g:codedark_conservative = 1" does not make a difference. Thanks.

**Comment by 9527KGG** [comment]
I tried on Windows OS. Same issue happened. Any suggestions?

**Comment by 9527KGG** [comment]
I echo the log. I see:
hi Function guifg=#DCDCAA ctermfg=brown

My .vimrc is just 
_syntax on

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tomasiser/vim-code-dark'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:-----
" ----------------------------------------------

colorscheme codedark_

**Comment by 9527KGG** [comment]
I think I know the reason:

Neither /usr/share/vim/vim80/syntax/cpp.vim nor /usr/share/vim/vim80/syntax/c.vim has the definition of "Function".

So it cannot show the yellow color for cpp function. Is that correct?

Seems gap between VS code....

**Comment by tomasiser** [comment]
Hello, yes I think this could be the reason. The syntax highlighting in Vim and in VS Code do not use the same rules so sometimes the coloring can be different and it cannot be fixed in this color scheme.

**Comment by 9527KGG** [comment]
Thanks. Seems an in-fixable gap until some one upgrades c/cpp syntax file.
