### ISSUE TITLE
support c++ keywords

### ISSUE THREAD

**Issue by YvesZHI** [tomasiser/vim-code-dark#40]
It doesn't seem that the current version of `vim-code-dark` supports C++ very well.

For example, the class name, the function don't have any color.

![xxx](https://user-images.githubusercontent.com/27804279/65226733-f72acd00-daf9-11e9-8401-c6e40b1b2456.JPG)

**Comment by yaoyuan0553** [comment]
This functionality probably requires semantics analysis depends on the situation. Checkout this other plugin that adds this functionality https://github.com/jeaye/color_coded

**Comment by zdzislaw-s** [comment]
I've created a PR #63 that uses [TagHighlight](https://github.com/abudden/taghighlight-automirror) to address this issue.
