### ISSUE TITLE
Comment's background should be #6A9955

### ISSUE THREAD

**Issue by ianpan870102** [tomasiser/vim-code-dark#58]
Loving this theme port, thanks for doing this. I noticed a slight inconsistency:
According to Visual Studio Code's official color palette (https://github.com/microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_vs.json)
comments should be colored "#6A9955"
Here's the snippet from Microsoft's repo for your reference:
```json
...
		{
			"scope": "comment",
			"settings": {
				"foreground": "#6A9955"
			}
		},
...
```

**Comment by ianpan870102** [comment]
Friendly ping.

**Comment by tomasiser** [comment]
Thanks for spotting this! I fixed it in the color scheme, but the readme will still state the wrong color for a while because I am not able to fix the image now.
