### ISSUE TITLE
Search result highlight is undetectable 

### ISSUE THREAD

**Issue by thongonary** [tomasiser/vim-code-dark#61]
The search result highlight is almost of the same color as background, making it very hard to detect. 

Here is an example in .vimrc
![image](https://user-images.githubusercontent.com/10479549/84960910-d4910900-b0b7-11ea-925f-940f89d76067.png)

Ideally it should pop out and be more visible like this
![image](https://user-images.githubusercontent.com/10479549/84961063-30f42880-b0b8-11ea-91c3-d480f5495060.png)

**Comment by gtsalles** [comment]
@thongonary which variable did you changed to make it more visible like this? 
I'm willing to change directly in the code as it's really hard to see the search result right now.

**Comment by thongonary** [comment]
@gtsalles I opened this issue with the hope that the creator could point me to the variable directly 😄 The "ideal" example of mine was created artificially a mouse highlight.

**Comment by gtsalles** [comment]
oh my hahahaha
I thought you had changed the variable directly.
I'll wait with you, then.
Thanks anyway ;)

**Comment by thongonary** [comment]
@gtsalles Now I just changed it directly in the recent pull request. While waiting for the maintainer to merge, you can just modify the code directly.

**Comment by gtsalles** [comment]
Great, thanks!

**Comment by tomasiser** [comment]
Solved by #62
