### ISSUE TITLE
Add compatability with NeoVim 0.5 and treesitter (should work out of the box?)

### ISSUE THREAD

**Issue by David-Else** [tomasiser/vim-code-dark#68]
> all colorscheme should be working already if you are using nvim-treesitter, as we leverage the standard highlight groups!

https://www.reddit.com/r/neovim/comments/imf9ty/is_there_already_some_colorscheme_leveraging/

When using the latest NeoVim nightly with https://github.com/nvim-treesitter/nvim-treesitter and vim-code-dark the results look bad. Is this expected or a bug? The syntax highlighting with treesitter is much better, but the keywords are not purple anymore and there are other things wrong.

## TypeScript + NeoVim 0.5 With treesitter next to VS Code
![vim-vs-vscode-neovim-treesitter](https://user-images.githubusercontent.com/12832280/96731195-e4df2a80-13ae-11eb-8cd5-c6032f1ffd5f.png)

## TypeScript + NeoVim 0.5 Without treesitter next to VS Code

![without-tree-sitter](https://user-images.githubusercontent.com/12832280/96731916-b281fd00-13af-11eb-96eb-d2b31d0ca86f.png)

**Comment by tomasiser** [comment]
Hello! I don't think this is a problem of NeoVim, but of course you can try opening the same file in pure vim. The thing is that VS Code uses their own syntax highlighting engine, which is not exactly matching what vim does. This plugin, `vim-code-dark`, is just a color scheme, so it tries to match the colors as closely as possible, but this plugin by itself has nothing to do with the actual syntax highlighting algorithms. However, sometimes with some syntax highlighting plugins, you can perform some adjustments in our color scheme to get better results (for example, there are now two PRs open about C++, #51 and #63).

**Comment by David-Else** [comment]
Thanks for the info. I changed from the conservative theme and it looks a little better, but there is more work to do on TypeScript colors to make them look as good as Code (even if they are slightly different). Treesitter removes many of the aweful bugs in the old TypeScript highlighting engine, so the future is looking good for Neovim :)

**Comment by David-Else** [comment]
Not really a bug it seems, so closing it.
