### ISSUE TITLE
Comment coloring not consistent

### ISSUE THREAD

**Issue by AdamBD** [tomasiser/vim-code-dark#70]
Hello there,

Great theme first of all! Thanks for all the hard work on it.

I am using it in iterm2 / Neovim, and I am seeing an issue with how colors in comments look
[image](https://user-images.githubusercontent.com/1134525/97881289-e43d8100-1d2a-11eb-8f39-54c715723009.png)

Any idea why this happens?

**Comment by tomasiser** [comment]
Hi! Thank you!

Have you meanwhile managed to solve this problem somehow? :)

**Comment by AdamBD** [comment]
@tomasiser yes, apologies for not closing. The conflict was coming from a spellchecker plugin I was running. Nothing wrong with your plugin
