### ISSUE TITLE
(Typescript) Function name and type are not colorized

### ISSUE THREAD

**Issue by dylanbussone** [tomasiser/vim-code-dark#88]
VS code appearance:
<img width="455" alt="vscode" src="https://user-images.githubusercontent.com/854809/147294265-703848c2-9490-41b6-96b4-cbbaaaa1a7e1.png">

vim-code-dark appearance:
<img width="415" alt="vim-theme" src="https://user-images.githubusercontent.com/854809/147294274-f9c099aa-cfb8-4774-a62e-ebb17189dd29.png">

Minor thing but it would be nice to get the same colorization for this. Thanks for making this!

**Comment by Nils75owo** [comment]
I think this might be bc of your syntax hilighting not bc of the theme.
You could take a look at neovim with treesitter
