### ISSUE TITLE
Cant remove entire Background

### ISSUE THREAD

**Issue by ThePaulCraft** [tomasiser/vim-code-dark#89]
I cant remove the entire background when using the codedark theme. Gruvbox for example hasn't this problem.
![image](https://user-images.githubusercontent.com/61984114/151866587-8fbc0588-d565-46e7-bb52-dc124b801d27.png)

for removing the background I use the following code in my init.vim:
```
highlight Normal ctermbg=none
highlight NonText ctermbg=none
highlight Normal guibg=none
highlight NonText guibg=none
highlight clear LineNr
highlight clear SignColumn
```

I use NeoVim 0.6.1

**Comment by williamalvarez92** [comment]
@PythonPizzaDE did you solve it?

**Comment by williamalvarez92** [comment]
I found it, in case someone is wondering. You can change it in the color vim file. Under
`call <sid>hi('EndOfBuffer', s:cdLineNumber, s:cdBack, 'none', {})`

Change `s:cdBack` to `s:cdNone`
