### ISSUE TITLE
Same colors in diff

### ISSUE THREAD

**Issue by derzhavin3016** [tomasiser/vim-code-dark#95]
As you can see, `DiffChange` option, which highlights the whole line with changes has color `DiffRedDark`, and `DiffText` option, which highlits the exact part of line that changed has color `DiffRedLight`
https://github.com/tomasiser/vim-code-dark/blob/7fe0dc672b20ef62962494560a0bc656fb237346/colors/codedark.vim#L144-L146

But definitions of these colors refers to the same xterm 256 colors which makes exact diff impossible to find in line
https://github.com/tomasiser/vim-code-dark/blob/7fe0dc672b20ef62962494560a0bc656fb237346/colors/codedark.vim#L95-L96

**Comment by saccarosium** [comment]
@tomasiser I think this can be closed since #103.

**Comment by derzhavin3016** [comment]
> @tomasiser I think this can be closed since #103.

Yes, now it looks better, thanks!
