### ISSUE TITLE
Plugin not working properly for js files

### ISSUE THREAD

**Issue by hasanmubarok9** [tomasiser/vim-code-dark#99]
Hello, I really like the colorschema of this plugin and I've been using it for a few days, but recently I realized this theme doesn't apply well to js files, but it works fine for ts.

my `.vimrc`: [.vimrc](https://github.com/hasanmubarok9/dotfiles/blob/main/.vimrc)

<img width="1013" alt="Screen Shot 2022-06-12 at 12 44 35" src="https://user-images.githubusercontent.com/45934721/173217528-b52fff79-2d83-416d-8b34-29aa8ba59db1.png">
<img width="1022" alt="Screen Shot 2022-06-12 at 12 45 12" src="https://user-images.githubusercontent.com/45934721/173217530-957c6f8c-d6fd-4e42-8b0a-9cb84e7216a9.png">

**Comment by LordPax** [comment]
I don't see "pangloss/vim-javascript" in your vimrc, you need this to improve the colorization of js

**Comment by LordPax** [comment]
hello @hasanmubarok9 your problem is solved ?

**Comment by PsiKai** [comment]
> I don't see "pangloss/vim-javascript" in your vimrc, you need this to improve the colorization of js

I have the same problem as the poster, and this plugin fixed it.

**Comment by tomasiser** [comment]
Thank you for reporting how to fix it. In general, a color scheme in Vim is a very "dumb" plugin that only provides a table of which colors should be applied to which syntax groups. However, the color scheme itself is not responsible for recognizing the syntax itself. For that, you need different plugins for the corresponding programming languages. In this case, the colors for JavaScript are defined in the color scheme, but how to recognize the JavaScript tokens is defined in another plugin outside of this color scheme. So typically you need multiple plugins and the color scheme is only one of them.
